// Helper to create dates relative to now
function daysFromNow(days: number): string {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString();
}

// ─── USERS ────────────────────────────────────────────────
// Passwords are plaintext here — the pre-save hook will hash them
export const users = [
  { username: 'jsmith', email: 'jsmith@example.com', password: 'password123' },
  { username: 'amiller', email: 'amiller@example.com', password: 'password123' },
  { username: 'klee', email: 'klee@example.com', password: 'password123' },
  { username: 'tjones', email: 'tjones@example.com', password: 'password123' },
  { username: 'rbrown', email: 'rbrown@example.com', password: 'password123' },
  { username: 'caleb', email: 'caleb@example.com', password: 'password123' },
];

// ─── EVENTS ───────────────────────────────────────────────
// organizer will be assigned in the seed script
export const events = [
  // Orlando events
  {
    title: 'Orlando Tech Meetup',
    description: 'Monthly gathering of Orlando developers. Lightning talks, networking, and pizza. All skill levels welcome!',
    startDate: daysFromNow(7),
    endDate: daysFromNow(7),
    location: { type: 'Point' as const, coordinates: [-81.3792, 28.5383] },
    address: 'Orlando, FL',
    venue: 'UCF Student Union',
    category: 'Networking',
    capacity: 50,
    isPublic: true,
  },
  {
    title: 'Summer Music Festival',
    description: 'Two days of amazing live music featuring local and regional artists. Food trucks, craft vendors, and family-friendly activities throughout the weekend.',
    startDate: daysFromNow(14),
    endDate: daysFromNow(15),
    location: { type: 'Point' as const, coordinates: [-81.3789, 28.5422] },
    address: 'Orlando, FL',
    venue: 'Lake Eola Park',
    category: 'Music',
    capacity: 500,
    isPublic: true,
  },
  {
    title: 'Intro to React Workshop',
    description: 'Hands-on workshop covering React fundamentals: components, state, hooks, and routing. Bring your laptop!',
    startDate: daysFromNow(10),
    endDate: daysFromNow(10),
    location: { type: 'Point' as const, coordinates: [-81.3992, 28.5983] },
    address: 'Orlando, FL',
    venue: 'Orlando Public Library',
    category: 'Workshop',
    capacity: 30,
    isPublic: true,
  },
  {
    title: '5K Charity Run',
    description: 'Annual charity run benefiting local food banks. All ages and paces welcome. Registration includes a t-shirt and post-race refreshments.',
    startDate: daysFromNow(21),
    endDate: daysFromNow(21),
    location: { type: 'Point' as const, coordinates: [-81.3732, 28.5432] },
    address: 'Orlando, FL',
    venue: 'Lake Eola Park',
    category: 'Sports',
    capacity: 200,
    isPublic: true,
  },
  {
    title: 'Board Game Social',
    description: 'Casual board game night. We have a library of 100+ games or bring your own. Snacks provided!',
    startDate: daysFromNow(5),
    endDate: daysFromNow(5),
    location: { type: 'Point' as const, coordinates: [-81.3510, 28.5560] },
    address: 'Orlando, FL',
    venue: 'The Geek Easy',
    category: 'Social',
    capacity: 40,
    isPublic: true,
  },

  // Miami events
  {
    title: 'React Summit Florida',
    description: 'Two-day conference featuring talks from React core team members and industry leaders. Workshops, networking, and an afterparty.',
    startDate: daysFromNow(30),
    endDate: daysFromNow(31),
    location: { type: 'Point' as const, coordinates: [-80.1918, 25.7617] },
    address: 'Miami, FL',
    venue: 'Miami Beach Convention Center',
    category: 'Conference',
    capacity: 500,
    isPublic: true,
  },
  {
    title: 'Miami Food Truck Rally',
    description: 'Over 30 food trucks from across South Florida. Live music, craft beer, and family fun.',
    startDate: daysFromNow(12),
    endDate: daysFromNow(12),
    location: { type: 'Point' as const, coordinates: [-80.1340, 25.7907] },
    address: 'Miami, FL',
    venue: 'Wynwood Marketplace',
    category: 'Food & Drink',
    capacity: 300,
    isPublic: true,
  },
  {
    title: 'Salsa Dancing Night',
    description: 'Beginner-friendly salsa class followed by open dancing. No partner needed!',
    startDate: daysFromNow(8),
    endDate: daysFromNow(8),
    location: { type: 'Point' as const, coordinates: [-80.1978, 25.7747] },
    address: 'Miami, FL',
    venue: 'Ball & Chain',
    category: 'Arts',
    capacity: 80,
    isPublic: true,
  },
  {
    title: 'Miami Startup Pitch Night',
    description: 'Watch 10 early-stage startups pitch to a panel of investors. Network with founders and VCs afterward.',
    startDate: daysFromNow(18),
    endDate: daysFromNow(18),
    location: { type: 'Point' as const, coordinates: [-80.1936, 25.7650] },
    address: 'Miami, FL',
    venue: 'The LAB Miami',
    category: 'Networking',
    capacity: 100,
    isPublic: true,
  },

  // Tampa events
  {
    title: 'Tampa Bay Craft Beer Festival',
    description: 'Sample over 200 craft beers from 50+ local and regional breweries. Live music and food vendors.',
    startDate: daysFromNow(25),
    endDate: daysFromNow(25),
    location: { type: 'Point' as const, coordinates: [-82.4572, 27.9506] },
    address: 'Tampa, FL',
    venue: 'Curtis Hixon Park',
    category: 'Food & Drink',
    capacity: 400,
    isPublic: true,
  },
  {
    title: 'Yoga in the Park',
    description: 'Free outdoor yoga session for all levels. Bring your own mat and water.',
    startDate: daysFromNow(3),
    endDate: daysFromNow(3),
    location: { type: 'Point' as const, coordinates: [-82.4612, 27.9476] },
    address: 'Tampa, FL',
    venue: 'Bayshore Boulevard',
    category: 'Sports',
    isPublic: true,
  },
  {
    title: 'Watercolor Painting Class',
    description: 'Learn basic watercolor techniques in this beginner-friendly class. All materials provided.',
    startDate: daysFromNow(9),
    endDate: daysFromNow(9),
    location: { type: 'Point' as const, coordinates: [-82.4530, 27.9480] },
    address: 'Tampa, FL',
    venue: 'Tampa Museum of Art',
    category: 'Arts',
    capacity: 20,
    isPublic: true,
  },
  {
    title: 'Tampa Dev Conference',
    description: 'Full-day developer conference covering web, mobile, and cloud technologies. Lunch included.',
    startDate: daysFromNow(35),
    endDate: daysFromNow(35),
    location: { type: 'Point' as const, coordinates: [-82.4592, 27.9456] },
    address: 'Tampa, FL',
    venue: 'Tampa Convention Center',
    category: 'Conference',
    capacity: 250,
    isPublic: true,
  },

  // New York events
  {
    title: 'NYC Jazz Night',
    description: 'Live jazz performances from some of the best musicians in the city. Intimate venue with cocktails.',
    startDate: daysFromNow(6),
    endDate: daysFromNow(6),
    location: { type: 'Point' as const, coordinates: [-74.0060, 40.7128] },
    address: 'New York, NY',
    venue: 'Blue Note Jazz Club',
    category: 'Music',
    capacity: 120,
    isPublic: true,
  },
  {
    title: 'Central Park Photography Walk',
    description: 'Guided photography walk through Central Park. Learn composition, lighting, and editing tips. All camera types welcome.',
    startDate: daysFromNow(11),
    endDate: daysFromNow(11),
    location: { type: 'Point' as const, coordinates: [-73.9654, 40.7829] },
    address: 'New York, NY',
    venue: 'Central Park',
    category: 'Workshop',
    capacity: 25,
    isPublic: true,
  },
  {
    title: 'NYC Marathon Training Group',
    description: 'Weekly group runs to prepare for the NYC Marathon. All paces welcome. Meet at the south entrance.',
    startDate: daysFromNow(4),
    endDate: daysFromNow(4),
    location: { type: 'Point' as const, coordinates: [-73.9742, 40.7681] },
    address: 'New York, NY',
    venue: 'Central Park South Entrance',
    category: 'Sports',
    capacity: 50,
    isPublic: true,
  },
  {
    title: 'Broadway Trivia Night',
    description: 'Test your knowledge of Broadway musicals! Teams of up to 6. Prizes for the top 3 teams.',
    startDate: daysFromNow(16),
    endDate: daysFromNow(16),
    location: { type: 'Point' as const, coordinates: [-73.9857, 40.7580] },
    address: 'New York, NY',
    venue: "Playwright's Irish Pub",
    category: 'Social',
    capacity: 60,
    isPublic: true,
  },

  // Los Angeles events
  {
    title: 'LA Indie Film Screening',
    description: 'Screening of three award-winning short films followed by a Q&A with the directors.',
    startDate: daysFromNow(13),
    endDate: daysFromNow(13),
    location: { type: 'Point' as const, coordinates: [-118.2437, 34.0522] },
    address: 'Los Angeles, CA',
    venue: 'The Egyptian Theatre',
    category: 'Arts',
    capacity: 150,
    isPublic: true,
  },
  {
    title: 'Taco Festival LA',
    description: 'Over 50 taco vendors competing for the Golden Taco award. Live music and margaritas.',
    startDate: daysFromNow(20),
    endDate: daysFromNow(20),
    location: { type: 'Point' as const, coordinates: [-118.2615, 34.0425] },
    address: 'Los Angeles, CA',
    venue: 'Grand Park',
    category: 'Food & Drink',
    capacity: 1000,
    isPublic: true,
  },
  {
    title: 'Sunset Beach Volleyball Tournament',
    description: 'Doubles beach volleyball tournament. All skill levels. Registration fee includes lunch and a tournament t-shirt.',
    startDate: daysFromNow(28),
    endDate: daysFromNow(28),
    location: { type: 'Point' as const, coordinates: [-118.4695, 34.0195] },
    address: 'Santa Monica, CA',
    venue: 'Santa Monica Beach',
    category: 'Sports',
    capacity: 64,
    isPublic: true,
  },
  {
    title: 'AI & Machine Learning Meetup',
    description: 'Monthly meetup discussing the latest in AI/ML. This month: practical applications of LLMs in production.',
    startDate: daysFromNow(17),
    endDate: daysFromNow(17),
    location: { type: 'Point' as const, coordinates: [-118.3965, 33.9425] },
    address: 'Los Angeles, CA',
    venue: 'Google LA Office',
    category: 'Networking',
    capacity: 80,
    isPublic: true,
  },
  {
    title: 'Open Mic Comedy Night',
    description: 'Try your hand at standup or just come to laugh. Sign up starts at 7pm, show at 8pm.',
    startDate: daysFromNow(22),
    endDate: daysFromNow(22),
    location: { type: 'Point' as const, coordinates: [-118.3287, 34.0966] },
    address: 'Los Angeles, CA',
    venue: 'The Comedy Store',
    category: 'Other',
    capacity: 100,
    isPublic: true,
  },

  // Caleb's events (mix of public and private)
  {
    title: 'Full-Stack Study Group',
    description: 'Weekly study group for UCF back-end development students. We cover MERN stack topics, work through assignments together, and prep for exams.',
    startDate: daysFromNow(2),
    endDate: daysFromNow(2),
    location: { type: 'Point' as const, coordinates: [-81.3992, 28.5983] },
    address: 'Orlando, FL',
    venue: 'UCF Library',
    category: 'Workshop',
    capacity: 15,
    isPublic: true,
  },
  {
    title: 'Project Demo Night',
    description: 'Informal gathering to demo our final projects before presentation day. Get feedback from peers in a low-pressure setting.',
    startDate: daysFromNow(19),
    endDate: daysFromNow(19),
    location: { type: 'Point' as const, coordinates: [-81.3789, 28.5422] },
    address: 'Orlando, FL',
    venue: 'UCF Student Union',
    category: 'Networking',
    capacity: 25,
    isPublic: true,
  },
  {
    title: 'Private Birthday Party',
    description: 'Birthday celebration at my place. Friends and family only — RSVP so I know how much food to get!',
    startDate: daysFromNow(24),
    endDate: daysFromNow(24),
    location: { type: 'Point' as const, coordinates: [-81.3510, 28.5560] },
    address: 'Orlando, FL',
    category: 'Social',
    capacity: 30,
    isPublic: false,
  },
  {
    title: 'Private LAN Party',
    description: 'Invite-only gaming night. Bring your own rig or use one of the spare setups. Pizza and energy drinks provided.',
    startDate: daysFromNow(10),
    endDate: daysFromNow(11),
    location: { type: 'Point' as const, coordinates: [-81.3510, 28.5560] },
    address: 'Orlando, FL',
    category: 'Other',
    capacity: 12,
    isPublic: false,
  },
];

// ─── RSVPS ────────────────────────────────────────────────
// user and event refs will be assigned in the seed script
export const rsvps = [
  { status: 'attending' },
  { status: 'attending' },
  { status: 'maybe' },
  { status: 'attending' },
  { status: 'attending' },
  { status: 'maybe' },
  { status: 'attending' },
  { status: 'attending' },
  { status: 'attending' },
  { status: 'maybe' },
  { status: 'attending' },
  { status: 'attending' },
  { status: 'attending' },
  { status: 'maybe' },
  { status: 'attending' },
  { status: 'attending' },
  { status: 'attending' },
  { status: 'maybe' },
  { status: 'attending' },
  { status: 'attending' },
  { status: 'attending' },
  { status: 'maybe' },
  { status: 'attending' },
  { status: 'attending' },
  { status: 'attending' },
  { status: 'maybe' },
  { status: 'attending' },
  { status: 'attending' },
  { status: 'attending' },
  { status: 'maybe' },
  { status: 'attending' },
  { status: 'attending' },
];
