name: EventLoop - Deploy to Render
env:
  deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}

on:
  pull_request:
    types: closed
    branches:
      - main

jobs:
  render-deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        run: curl "$deploy_url"
